import { writable } from 'svelte/store';
export const mapConfig = writable({
  "title": "Which EU countries have compulsory conscription?",
  "subtitle": "Out of the 27 countries in the EU 9 have a compulsory conscription",
  "colourSchemeClasses": 5,
  "data": "country,id,value,extraInfo,text_content,link_text,link_url_target,audio_url_1,audio_url_2,audio_url_3,image_url_source,image_url_target,video_url\nAustria,AT,1,TRUE,In 2006 compulsory military service was reduced to six months.,,,,,,,,\nBelgium,BE,0,FALSE,,,,,,,,,\nBulgaria,BG,0,FALSE,,,,,,,,,\nCyprus,CY,1,TRUE,Compulsory military service is 26 months,,,,,,,,\nCzechia,CZ,0,FALSE,,,,,,,,,\nGermany,DE,0,FALSE,,,,,,,,,\nDenmark,DK,1,TRUE,Compulsory military service lasts four to twelve months,,,,,,,,\nEstonia,EE,1,TRUE,Compulsory military service lasts eight to eleven months,,,,,,,,\nGreece,EL,1,TRUE,Compulsory military service lasts nine to twelve months,,,,,,,,\nSpain,ES,0,FALSE,,,,,,,,,\nFinland,FI,1,TRUE,Compulsory military service lasts six to twelve months,,,,,,,,\nFrance,FR,0,FALSE,,,,,,,,,\nCroatia,HR,0.000,FALSE,,,,,,,,,\nHungary,HU,0,FALSE,,,,,,,,,\nIreland,IE,0,FALSE,,,,,,,,,\nItaly,IT,0,FALSE,,,,,,,,,\nLithuania,LT,1,TRUE,Compulsory military service lasts nine months,,,,,,,,\nLuxembourg,LU,0,FALSE,,,,,,,,,\nLatvia,LV,1,TRUE,Compulsory military service lasts six months,,,,,,,,\nMalta,MT,0,FALSE,,,,,,,,,\nNetherlands,NL,0,FALSE,,,,,,,,,\nPoland,PL,0,FALSE,,,,,,,,,\nPortugal,PT,0,FALSE,,,,,,,,,\nRomania,RO,0,FALSE,,,,,,,,,\nSweden,SE,1,TRUE,Compulsory military service lasts twelve months,,,,,,,,\nSlovenia,SI,0,FALSE,,,,,,,,,\nSlovakia,SK,0,FALSE,,,,,,,,,",
  "parsedData": [
    {
      "country": "Austria",
      "id": "AT",
      "value": 1,
      "extraInfo": true,
      "text_content": "In 2006 compulsory military service was reduced to six months.",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Belgium",
      "id": "BE",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Bulgaria",
      "id": "BG",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Cyprus",
      "id": "CY",
      "value": 1,
      "extraInfo": true,
      "text_content": "Compulsory military service is 26 months",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Czechia",
      "id": "CZ",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Germany",
      "id": "DE",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Denmark",
      "id": "DK",
      "value": 1,
      "extraInfo": true,
      "text_content": "Compulsory military service lasts four to twelve months",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Estonia",
      "id": "EE",
      "value": 1,
      "extraInfo": true,
      "text_content": "Compulsory military service lasts eight to eleven months",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Greece",
      "id": "EL",
      "value": 1,
      "extraInfo": true,
      "text_content": "Compulsory military service lasts nine to twelve months",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Spain",
      "id": "ES",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Finland",
      "id": "FI",
      "value": 1,
      "extraInfo": true,
      "text_content": "Compulsory military service lasts six to twelve months",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "France",
      "id": "FR",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Croatia",
      "id": "HR",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Hungary",
      "id": "HU",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Ireland",
      "id": "IE",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Italy",
      "id": "IT",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Lithuania",
      "id": "LT",
      "value": 1,
      "extraInfo": true,
      "text_content": "Compulsory military service lasts nine months",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Luxembourg",
      "id": "LU",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Latvia",
      "id": "LV",
      "value": 1,
      "extraInfo": true,
      "text_content": "Compulsory military service lasts six months",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Malta",
      "id": "MT",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Netherlands",
      "id": "NL",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Poland",
      "id": "PL",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Portugal",
      "id": "PT",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Romania",
      "id": "RO",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Sweden",
      "id": "SE",
      "value": 1,
      "extraInfo": true,
      "text_content": "Compulsory military service lasts twelve months",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovenia",
      "id": "SI",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovakia",
      "id": "SK",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    }
  ],
  "datasetType": "binary",
  "datasetUnit": "percent",
  "percentRounded": false,
  "colourSchemeType": "sequential",
  "colourScheme": "red",
  "colourSchemeReverse": false,
  "headlineAvailable": true,
  "subheadlineAvailable": true,
  "tooltipAvailable": true,
  "scaleBarAvailable": true,
  "overrideScaleValues": false,
  "legendAvailable": true,
  "textSourceAvailable": true,
  "textSourceDescription": "Source",
  "textSource": "EUNews",
  "textNoteAvailable": true,
  "textNoteDescription": "Note",
  "textNote": "All other countries in the EU27 have a",
  "textDataAccessAvailable": true,
  "linkDataAccessDescription": "Access the data",
  "linkDataAccess": "https://www.eunews.it/en/2024/05/15/european-countries-back-to-discussing-compulsory-military-conscription-nine-still-have-it/",
  "legend1": "No data available",
  "legend1Color": "#E0E0E0",
  "customUnitLabelAvailable": false,
  "customUnitLabel": "",
  "tooltipExtraInfoLabel": "Click here",
  "translate": {
    "title": "Which EU countries have compulsory conscription?",
    "subtitle": "Out of the 27 countries in the EU 9 have a compulsory conscription",
    "textNoteDescription": "Note",
    "textNote": "All other countries in the EU27 have a",
    "textSourceDescription": "Source",
    "textSource": "EUNews",
    "linkDataAccessDescription": "Access the data",
    "legend1": "No data available",
    "tooltipExtraInfoLabel": "Click here",
    "extraInfo_AT": "In 2006 compulsory military service was reduced to six months.",
    "extraInfo_CY": "Compulsory military service is 26 months",
    "extraInfo_DK": "Compulsory military service lasts four to twelve months",
    "extraInfo_EE": "Compulsory military service lasts eight to eleven months",
    "extraInfo_EL": "Compulsory military service lasts nine to twelve months",
    "extraInfo_FI": "Compulsory military service lasts six to twelve months",
    "extraInfo_LT": "Compulsory military service lasts nine months",
    "extraInfo_LV": "Compulsory military service lasts six months",
    "extraInfo_SE": "Compulsory military service lasts twelve months"
  },
  "clusters": [],
  "colorScale": null,
  "extraInfo_AT": "In 2006 compulsory military service was reduced to six months.",
  "extraInfo_CY": "Compulsory military service is 26 months",
  "extraInfo_DK": "Compulsory military service lasts four to twelve months",
  "extraInfo_EE": "Compulsory military service lasts eight to eleven months",
  "extraInfo_EL": "Compulsory military service lasts nine to twelve months",
  "extraInfo_FI": "Compulsory military service lasts six to twelve months",
  "extraInfo_LT": "Compulsory military service lasts nine months",
  "extraInfo_LV": "Compulsory military service lasts six months",
  "extraInfo_SE": "Compulsory military service lasts twelve months"
});